# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ProcessDups.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblImage = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblImage.sizePolicy().hasHeightForWidth())
        self.lblImage.setSizePolicy(sizePolicy)
        self.lblImage.setMinimumSize(QtCore.QSize(600, 0))
        self.lblImage.setObjectName("lblImage")
        self.verticalLayout_2.addWidget(self.lblImage)
        self.gbButtons = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbButtons.sizePolicy().hasHeightForWidth())
        self.gbButtons.setSizePolicy(sizePolicy)
        self.gbButtons.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gbButtons.setTitle("")
        self.gbButtons.setObjectName("gbButtons")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbButtons)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbtnRestart = QtWidgets.QPushButton(self.gbButtons)
        self.pbtnRestart.setObjectName("pbtnRestart")
        self.horizontalLayout_3.addWidget(self.pbtnRestart)
        self.pbtnSwap = QtWidgets.QPushButton(self.gbButtons)
        self.pbtnSwap.setObjectName("pbtnSwap")
        self.horizontalLayout_3.addWidget(self.pbtnSwap)
        self.pbtnNotDup = QtWidgets.QPushButton(self.gbButtons)
        self.pbtnNotDup.setObjectName("pbtnNotDup")
        self.horizontalLayout_3.addWidget(self.pbtnNotDup)
        self.pbtnDup = QtWidgets.QPushButton(self.gbButtons)
        self.pbtnDup.setObjectName("pbtnDup")
        self.horizontalLayout_3.addWidget(self.pbtnDup)
        self.verticalLayout_2.addWidget(self.gbButtons)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblImage.setText(_translate("MainWindow", "Image"))
        self.pbtnRestart.setText(_translate("MainWindow", "Restart"))
        self.pbtnSwap.setText(_translate("MainWindow", "Swap"))
        self.pbtnNotDup.setText(_translate("MainWindow", "Not Dup"))
        self.pbtnDup.setText(_translate("MainWindow", "Dup"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())